### ISSUE TITLE
Maintenance improvements

### ISSUE THREAD

**Issue by DinanII** [MatthijsSchoonen/Barroc-Intens#32]
# Barroc Intens Points of Improvement

## Maintenance Visit Detail
- &lt; sign op Back to Overview button in Appointment Detail

## MaintenanceAppointment Create
- Confirmation appointment has been created.
- Auto redirect to Overview once appointment is created

## MaintenanceAppointment Overview
- Ability to switch weeks
- Week number notation

## General
- Roles table for users.
Current roles: Admin, employee and customer

**Comment by MatthijsSchoonen** [comment]
Als je op de visit OverView bent kan je  niet direct terug naar het dashboard verder werk het goed
