### ISSUE TITLE
Als financieel medewerkerwil ik makkelijk een factuur kunnen opstellen voor de aansluitkosten vaneen koffiezetapparaat. Zo voorkom ik dat iedere factuur er anders uitziet en dat ik mogelijk rekenfouten maak

### ISSUE THREAD

**Issue by MatthijsSchoonen** [MatthijsSchoonen/Barroc-Intens#4]

**Comment by MatthijsSchoonen** [comment]
opslaan in database

**Comment by DinanII** [comment]
Input
	Customer Information
		Why there are inputs for name and address? This information is already included in the attached
		Company entry? Because it may be another location? This is not clearly mentioned.
	Products
		As a user, I am unable to enter the product amount.

Procesing
	Why there is a separate table "customerInvoices", since there is already a table named "invoices".
	The following inputs are not saved:
	Name,
	Address,
	Connection Costs,
	Vat (%),
	Start date (the current DateTime gets stored instead)
	End date (the current DateTime gets stored instead)
	
	Products do get stored in junction table, however there is no possibility to mention the
	product amount as mentioned earlier, while there is a field for it. And there is a unnecessary field named
	"PricePerUnit", this is already mentioned in products table.
